# Generated by Django 4.1.7 on 2023-06-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invlocation',
            name='address2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
