# Generated by Django 4.1.7 on 2023-06-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_invlocation_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invlocation',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='invlocation',
            name='address2',
        ),
    ]
