# Generated by Django 4.1.7 on 2023-06-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_address1_invlocation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invlocation',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
